name: smart_tour
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  localization: ^2.1.0
  flutter_launcher_icons: "^0.13.1"
  dio: ^5.1.1
  gif: ^2.2.0
  http: ^1.0.0
  shared_preferences: ^2.1.2
  provider: ^6.0.5
  flutter_carousel_slider: ^1.1.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/images/splash.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "lib/assets/images/splash.png"

flutter:

  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/i18n/
    - lib/assets/fonts/
    - lib/assets/images/
    - lib/assets/images/travels/
  
  fonts:
  - family: Tiro Tamil
    fonts:
      - asset: lib/assets/fonts/TiroTamil-Regular.ttf
      - asset: lib/assets/fonts/TiroTamil-Italic.ttf