name: smart_tour
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  localization: ^2.1.0
  flutter_launcher_icons: "^0.12.0"
  flutter_native_splash: ^2.2.19
  dio: ^5.1.1
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
  google_api_headers: ^1.1.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_maps_flutter: ^2.1.1
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  image: lib/assets/images/splash.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/splash.png"
  adaptative_icon_foreground: "lib/assets/images/splash.png"

flutter:

  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/i18n/
    - lib/assets/images/