import 'package:flutter/material.dart';

import 'interests_model.dart';

List<Interests> interestsList = [
  Interests(name: 'Aventura', iconData: Icons.explore),
  Interests(name: 'Animais', iconData: Icons.pets),
  Interests(name: 'Arte', iconData: Icons.palette),
  Interests(name: 'Artesanato', iconData: Icons.create),
  Interests(name: 'Cachoeira', iconData: Icons.waterfall_chart),
  Interests(name: 'Caminhada', iconData: Icons.directions_walk),
  Interests(name: 'Caverna', iconData: Icons.landscape),
  Interests(name: 'Compras', iconData: Icons.shopping_cart),
  Interests(name: 'Cultura', iconData: Icons.public),
  Interests(name: 'Dunas', iconData: Icons.terrain),
  Interests(name: 'Espiritualidade', iconData: Icons.spa),
  Interests(name: 'Esportes', iconData: Icons.sports_soccer),
  Interests(name: 'Eventos', iconData: Icons.event),
  Interests(name: 'Experiências locais', iconData: Icons.local_activity),
  Interests(name: 'Família', iconData: Icons.family_restroom),
  Interests(name: 'Festas', iconData: Icons.party_mode),
  Interests(name: 'Florestas', iconData: Icons.eco),
  Interests(name: 'Fotografia', iconData: Icons.camera_alt),
  Interests(name: 'Gastronomia', iconData: Icons.restaurant),
  Interests(name: 'História', iconData: Icons.history),
  Interests(name: 'Ilhas', iconData: Icons.nature),
  Interests(name: 'Lagos', iconData: Icons.water),
  Interests(name: 'Lazer', iconData: Icons.sports_handball),
  Interests(name: 'Montanha', iconData: Icons.terrain),
  Interests(name: 'Monumento', iconData: Icons.account_balance),
  Interests(name: 'Mergulho', iconData: Icons.scuba_diving),
  Interests(name: 'Museus', iconData: Icons.museum),
  Interests(name: 'Musica', iconData: Icons.music_note),
  Interests(name: 'Natureza', iconData: Icons.nature_people),
  Interests(name: 'Parques', iconData: Icons.park),
  Interests(name: 'Passeios', iconData: Icons.directions),
  Interests(name: 'Pôr do sol', iconData: Icons.wb_sunny),
  Interests(name: 'Praia', iconData: Icons.beach_access),
  Interests(name: 'Rio', iconData: Icons.water),
  Interests(name: 'Romance', iconData: Icons.favorite),
  Interests(name: 'Spa', iconData: Icons.spa),
  Interests(name: 'Surf', iconData: Icons.surfing),
  Interests(name: 'Teatro', iconData: Icons.theater_comedy),
  Interests(name: 'Trilha', iconData: Icons.hiking),
  Interests(name: 'Turismo religioso', iconData: Icons.church),
  Interests(name: 'Vista panorâmica', iconData: Icons.panorama),
];
