import 'package:flutter/material.dart';

import 'interests_model.dart';

List<Interests> interestsList = [
  Interests(name: 'Adventure', iconData: Icons.directions_bike),
  Interests(name: 'Amusement parks', iconData: Icons.local_play),
  Interests(name: 'Archaeological sites', iconData: Icons.account_balance),
  Interests(name: 'Architecture', iconData: Icons.location_city),
  Interests(name: 'Art', iconData: Icons.brush),
  Interests(name: 'Beaches', iconData: Icons.beach_access),
  Interests(name: 'Bike tours', iconData: Icons.directions_bike),
  Interests(name: 'Botanical gardens', iconData: Icons.local_florist),
  Interests(name: 'Brewery', iconData: Icons.local_drink),
  Interests(name: 'Churches', iconData: Icons.account_balance),
  Interests(name: 'Climbing', iconData: Icons.landscape),
  Interests(name: 'Coral reefs', iconData: Icons.beach_access),
  Interests(name: 'Culture', iconData: Icons.palette),
  Interests(name: 'Dance', iconData: Icons.music_note),
  Interests(name: 'Ecotourism', iconData: Icons.nature),
  Interests(name: 'Events', iconData: Icons.event),
  Interests(name: 'Family vacations', iconData: Icons.family_restroom),
  Interests(name: 'Festivals', iconData: Icons.event),
  Interests(name: 'Forests', iconData: Icons.nature),
  Interests(name: 'Gastronomy', iconData: Icons.restaurant),
  Interests(name: 'Golf', iconData: Icons.golf_course),
  Interests(name: 'Helicopter tours', iconData: Icons.local_airport),
  Interests(name: 'Historical sites', iconData: Icons.account_balance),
  Interests(name: 'History', iconData: Icons.history),
  Interests(name: 'Hiking', iconData: Icons.hiking),
  Interests(name: 'Islands', iconData: Icons.beach_access),
  Interests(name: 'Kitesurfing', iconData: Icons.kitesurfing),
  Interests(name: 'Local experiences', iconData: Icons.place),
  Interests(name: 'Luxury', iconData: Icons.star),
  Interests(name: 'Markets', iconData: Icons.shopping_basket),
  Interests(name: 'Mountain', iconData: Icons.landscape),
  Interests(name: 'Museums', iconData: Icons.museum),
  Interests(name: 'Natural wonders', iconData: Icons.landscape),
  Interests(name: 'Nature', iconData: Icons.nature),
  Interests(name: 'Nightlife', iconData: Icons.nightlife),
  Interests(name: 'National parks', iconData: Icons.landscape),
  Interests(name: 'Ocean', iconData: Icons.beach_access),
  Interests(name: 'Photography', iconData: Icons.camera),
  Interests(name: 'Relaxation', iconData: Icons.spa),
  Interests(name: 'Religious tourism', iconData: Icons.account_balance),
  Interests(name: 'Resorts', iconData: Icons.hotel),
  Interests(name: 'River', iconData: Icons.water),
  Interests(name: 'Romance', iconData: Icons.favorite),
  Interests(name: 'Rural tourism', iconData: Icons.landscape),
  Interests(name: 'Ruins', iconData: Icons.museum),
  Interests(name: 'Safaris', iconData: Icons.nature_people),
  Interests(name: 'Sanctuaries', iconData: Icons.account_balance),
  Interests(name: 'Shopping', iconData: Icons.shopping_cart),
  Interests(name: 'Sightseeing tours', iconData: Icons.directions),
  Interests(name: 'Skiing', iconData: Icons.snowboarding),
  Interests(name: 'Snowboarding', iconData: Icons.snowboarding),
  Interests(name: 'Spirituality', iconData: Icons.account_balance),
  Interests(name: 'Spa', iconData: Icons.spa),
  Interests(name: 'Surfing', iconData: Icons.surfing),
  Interests(name: 'Theater', iconData: Icons.theater_comedy),
  Interests(name: 'Train tours', iconData: Icons.train),
  Interests(name: 'Villages', iconData: Icons.location_city),
  Interests(name: 'Volcanoes', iconData: Icons.volcano),
  Interests(name: 'Water parks', iconData: Icons.pool),
  Interests(name: 'Wildlife', iconData: Icons.pets),
  Interests(name: 'Wine tasting', iconData: Icons.wine_bar),
];
